import os

LIFESIM_OUTER_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIFESIM_INNER_DIR = os.path.join(LIFESIM_OUTER_DIR, "lifesim")
PPOP_DIR = os.path.join(LIFESIM_OUTER_DIR, "PPop")
PPOP_DATA_DIR = os.path.join(PPOP_DIR, "data")
PPOP_STAR_DIR = os.path.join(PPOP_DIR, "StarCatalogs")
LIFESIM_DATA_DIR = os.path.join(LIFESIM_OUTER_DIR, "run","lifesim","data")
HWO_DATA_DIR = os.path.join(LIFESIM_OUTER_DIR, "run","hwo","data")
PLOTS_DIR = os.path.join(LIFESIM_OUTER_DIR, "output", "figures")
LOGGING = os.path.join(LIFESIM_OUTER_DIR, "run", "logging")
#Hongyi added for kepler data 5/18
KEPLER_DATA_DIR = os.path.join(LIFESIM_OUTER_DIR, "run", "kepler", "data")
TESS_DATA_DIR = os.path.join(LIFESIM_OUTER_DIR, "run", "tess", "data")
FLAT_UNIVERSE_DATA_DIR = os.path.join(LIFESIM_OUTER_DIR, "run", "flat_universe", "data")
DATA_DIR = os.path.join(LIFESIM_OUTER_DIR, "data")
SILICON_CURVE = os.path.join(DATA_DIR, "silicon_curve.ddat")
MY_OUTPUTS_DIR = os.path.join(LIFESIM_OUTER_DIR, "my_outputs")
EXOPLANET_CSV_DIR = os.path.join(DATA_DIR, "exoplanet_csv")
KOI_CUMULATIVE_CSV = os.path.join(EXOPLANET_CSV_DIR, "koi_cumulative_stellar.csv")
EXOFOP_TOI_CSV = os.path.join(EXOPLANET_CSV_DIR, "exofop_toi.csv")
PSCOMPPARS_CSV = os.path.join(EXOPLANET_CSV_DIR, "pscomppars_2026.csv")
